# Replace the placeholders ([YOUR_LOCALHOST_URL], [YOUR_API_KEY], 
# [YOUR_RENEWABLE_SHARE_KEY], and [YOUR_TOTAL_ENERGY_SAVED_KEY]) with 
# your actual values when you're ready to use the file. This ensures 
# that sensitive information is not exposed in the public repository.

### hello world
GET [YOUR_LOCALHOST_URL]/

### Push on/off schedule
GET [YOUR_LOCALHOST_URL]/push_schedule?key=[YOUR_API_KEY]&values=on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,off,off,off,off

### GET on/off schedule
GET [YOUR_LOCALHOST_URL]/schedule?key=[YOUR_API_KEY]

### Push renewable share for 24h
GET [YOUR_LOCALHOST_URL]/push_renewable_share?key=[YOUR_RENEWABLE_SHARE_KEY]&data=1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8,9,1,2,3,4,5,6

### GET renewable share for 24h
GET [YOUR_LOCALHOST_URL]/get_renewable_share?key=[YOUR_RENEWABLE_SHARE_KEY]

### GET total energy saved
GET [YOUR_LOCALHOST_URL]/get_total_energy_saved?key=[YOUR_TOTAL_ENERGY_SAVED_KEY]

### Push total energy saved
GET [YOUR_LOCALHOST_URL]/push_total_energy_saved?key=[YOUR_TOTAL_ENERGY_SAVED_KEY]&value=99
